import { test, expect } from "@playwright/test";
import { observe } from "../../support/backend";
import { expectReply, handlerRuns, openChat, send } from "../../support/copilotkit";

test("a schema generated by useFrontendTool with nested objects, arrays and nullable values is accepted", async ({ page, request }) => {
  const { threadId } = await openChat(page, request, "deferred-title", { tools: "read_title,inspect" });
  await send(page, "What is the title?");

  await expectReply(page, 'Done: {"call_read_title_1":"Neuron Fixture"}');
  const audit = await observe(request, threadId);
  expect(audit.invocations[0].tools).toEqual(expect.arrayContaining(["inspect", "read_title"]));
});

test("an unmounted tool component is not declared, so the model cannot call it", async ({ page, request }) => {
  const { threadId, runs } = await openChat(page, request, "deferred-title", { tools: "read_text" });
  await send(page, "What is the title?");

  await expect.poll(async () => (await observe(request, threadId)).run?.status, { timeout: 15_000 }).toBe("failed");
  expect(await handlerRuns(page)).toEqual({});
  const audit = await observe(request, threadId);
  expect(audit.invocations).toHaveLength(0);
  expect(JSON.parse(runs[0]).tools.map((tool: { name: string }) => tool.name)).toEqual(["read_text", "probe"]);
});
