<?php

declare(strict_types=1);

namespace NeuronAI\Tests\Tools;

use NeuronAI\Exceptions\MissingCallbackParameter;
use NeuronAI\Tests\Stubs\StructuredOutput\Color;
use NeuronAI\Tests\Stubs\Tools\TestToolClassOnlyParentConstructor;
use NeuronAI\Tests\Stubs\Tools\TestToolClassOnlyParentConstructorFluent;
use NeuronAI\Tests\Stubs\Tools\TestToolClassWithParentConstructor;
use NeuronAI\Tests\Stubs\Tools\TestToolClassWithParentConstructorMixed;
use NeuronAI\Tools\ArrayProperty;
use NeuronAI\Tools\ObjectProperty;
use NeuronAI\Tools\PropertyType;
use NeuronAI\Tools\Tool;
use NeuronAI\Tools\ToolDefinition;
use NeuronAI\Tools\ToolInterface;
use NeuronAI\Tools\ToolProperty;
use PHPUnit\Framework\TestCase;
use Error;

class ToolTest extends TestCase
{
    public function test_tool_instance(): void
    {
        $tool = new ToolDefinition('example', 'example');
        $this->assertInstanceOf(ToolInterface::class, $tool);

        $tool->setInputs(null);
        $this->assertEquals([], $tool->getInputs());

        $tool->setCallId(null); // Tool call ID is not generated by all providers
        $this->assertEquals(null, $tool->getCallId());
        $tool->setCallId('test');
        $this->assertEquals('test', $tool->getCallId());
    }

    public function test_required_properties(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test';
            protected ?string $description = 'Test tool';
            public function __construct()
            {
                $this->addProperty(new ToolProperty('name', PropertyType::STRING, 'User name', true));
                $this->addProperty(new ToolProperty('surname', PropertyType::STRING, 'User surname', false));
                $this->addProperty(new ToolProperty('age', PropertyType::INTEGER, 'User age', true));
            }
            public function __invoke(): void
            {
            }
        };

        $properties = $tool->getRequiredProperties();
        $this->assertEquals(['name', 'age'], $properties);
    }

    public function test_missing_required_parameter_exception(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test';
            protected ?string $description = 'Test tool';
            public function __construct()
            {
                $this->addProperty(new ToolProperty('name', PropertyType::STRING, 'User name', true));
            }
            public function __invoke(string $name): string
            {
                return $name;
            }
        };

        $tool->setInputs([
            "test" => "test",
        ]);

        $this->expectException(MissingCallbackParameter::class);
        $this->expectExceptionMessage('Missing required parameter: name');

        $tool->execute();

        $tool->setInputs([]);

        $this->expectException(MissingCallbackParameter::class);
        $this->expectExceptionMessage('Missing required parameter: name');

        $tool->execute();
    }

    public function test_required_properties_with_mapped_object(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test';
            protected ?string $description = 'Test tool';
            public function __construct()
            {
                $this->addProperty(new ObjectProperty(
                    name: 'name',
                    description: 'User name',
                    required: true,
                    class: Color::class
                ));
            }
            public function __invoke(): void
            {
            }
        };

        $toolRequiredProperties = $tool->getRequiredProperties();
        /** @var ObjectProperty $objProperty */
        $objProperty = $tool->getProperties()[0];
        $objRequiredProperties = $objProperty->getRequiredProperties();
        $this->assertEquals(['name'], $toolRequiredProperties);
        $this->assertEquals(['r', 'g', 'b'], $objRequiredProperties);
    }

    public function test_tool_return_value(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test';
            protected ?string $description = 'Test tool';
            public function __invoke(): string
            {
                return 'test';
            }
        };
        $tool->execute();
        $this->assertEquals('test', $tool->getResult());

        $tool = new class () extends Tool {
            protected string $name = 'test';
            protected ?string $description = 'Test tool';
            public function __invoke(): array
            {
                return ['test'];
            }
        };
        $tool->execute();
        $this->assertEquals('["test"]', $tool->getResult());

        $tool = new class () extends Tool {
            protected string $name = 'test';
            protected ?string $description = 'Test tool';
            public function __invoke(): array
            {
                return ['foo' => 'bar'];
            }
        };
        $tool->execute();
        $this->assertEquals('{"foo":"bar"}', $tool->getResult());

        $tool = new class () extends Tool {
            protected string $name = 'test';
            protected ?string $description = 'Test tool';
            public function __invoke(): object
            {
                return new class () {
                    public function __toString(): string
                    {
                        return 'test';
                    }
                };
            }
        };
        $tool->execute();
        $this->assertEquals('test', $tool->getResult());
    }

    public function test_invalid_return_type(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test';
            protected ?string $description = 'Test tool';
            public function __invoke(): object
            {
                return new class () {};
            }
        };

        $this->expectException(Error::class);

        $tool->execute();
    }

    public function test_tool_optional_parameters(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test_tool';
            protected ?string $description = 'description';
            public function __construct()
            {
                $this->addProperty(new ToolProperty(
                    name: 'optional_prop_1',
                    type: PropertyType::STRING,
                    description: "description",
                    required: false,
                ));
                $this->addProperty(new ToolProperty(
                    name: 'optional_prop_2',
                    type: PropertyType::STRING,
                    description: "description",
                    required: false,
                ));
                $this->addProperty(new ToolProperty(
                    name: 'optional_prop_3',
                    type: PropertyType::STRING,
                    description: "description",
                    required: false,
                ));
            }
            public function __invoke(?string $optional_prop_1, ?string $optional_prop_2, ?string $optional_prop_3): array
            {
                return [
                    'optional_prop_1' => $optional_prop_1,
                    'optional_prop_2' => $optional_prop_2,
                    'optional_prop_3' => $optional_prop_3,
                ];
            }
        };

        // Example: none of the optional parameters are provided
        $tool->setInputs([]);

        $tool->execute();

        $this->assertEquals(
            '{"optional_prop_1":null,"optional_prop_2":null,"optional_prop_3":null}',
            $tool->getResult()
        );
    }

    public function test_tool_variadic_invocation_basic_properties(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'user_manager';
            protected ?string $description = 'Update user information';
            public function __construct()
            {
                $this->addProperty(new ToolProperty(
                    name: 'lastname',
                    type: PropertyType::STRING,
                    description: "The user lastname",
                    required: false,
                ));
                $this->addProperty(new ToolProperty(
                    name: 'firstname',
                    type: PropertyType::STRING,
                    description: "The user firstname",
                    required: false,
                ));
                $this->addProperty(new ToolProperty(
                    name: 'email',
                    type: PropertyType::STRING,
                    description: "The user email",
                    required: true,
                ));
                $this->addProperty(new ToolProperty(
                    name: 'language',
                    type: PropertyType::STRING,
                    description: "The user's language",
                    required: true,
                    enum: ['fr', 'en', 'it', 'de', 'es'],
                ));
            }
            public function __invoke(mixed ...$data): array
            {
                return $data;
            }
        };

        // Example: the user's last name is not provided
        $tool->setInputs([
            "firstname" => "John",
            "email" => "john.doe@example.com",
            "language" => "fr",
        ]);

        $tool->execute();

        $this->assertEquals(
            '{"lastname":null,"firstname":"John","email":"john.doe@example.com","language":"fr"}',
            $tool->getResult()
        );
    }

    public function test_tool_variadic_invocation_object_properties(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test_tool';
            protected ?string $description = 'description';
            public function __construct()
            {
                $this->addProperty(
                    new ObjectProperty(
                        name: 'obj_prop_1',
                        description: "description obj_prop_1",
                        required: true,
                        properties: [
                            new ToolProperty(
                                name: 'a',
                                type: PropertyType::STRING,
                                description: "description a",
                                required: true,
                            ),
                            new ToolProperty(
                                name: 'b',
                                type: PropertyType::STRING,
                                description: "description b",
                                required: true,
                            ),
                        ]
                    )
                );
                $this->addProperty(
                    new ObjectProperty(
                        name: 'obj_prop_2',
                        description: "description obj_prop_2",
                        required: false,
                        properties: [
                                new ToolProperty(
                                    name: 'x',
                                    type: PropertyType::STRING,
                                    description: "description x",
                                    required: true,
                                ),
                                new ToolProperty(
                                    name: 'y',
                                    type: PropertyType::STRING,
                                    description: "description y",
                                    required: true,
                                ),
                            ]
                    )
                );
            }
            public function __invoke(mixed ...$data): array
            {
                return $data;
            }
        };

        // Example, the second object property is not provided
        $tool->setInputs([
            "obj_prop_1" => [
                "a" => "a_input",
                "b" => "b_input",
            ],
        ]);

        $tool->execute();

        $this->assertEquals(
            '{"obj_prop_1":{"a":"a_input","b":"b_input"},"obj_prop_2":null}',
            $tool->getResult()
        );
    }

    public function test_tool_variadic_invocation_mapped_object_properties(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test_tool';
            protected ?string $description = 'description';
            public function __construct()
            {
                $this->addProperty(
                    new ObjectProperty(
                        name: 'color',
                        description: "description color",
                        required: true,
                        class: Color::class
                    )
                );
            }
            public function __invoke(mixed ...$data): array
            {
                return $data;
            }
        };

        $tool->setInputs([
            "color" => [
                "r" => 255,
                "g" => 127,
                "b" => 63,
            ],
        ]);

        $tool->execute();

        $this->assertEquals(
            '{"color":{"r":255,"g":127,"b":63}}',
            $tool->getResult()
        );
    }

    public function test_tool_variadic_invocation_array_properties(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test_tool';
            protected ?string $description = 'description';
            public function __construct()
            {
                $this->addProperty(
                    new ArrayProperty(
                        name: 'colors',
                        description: "description color",
                        required: true,
                        items: new ToolProperty(
                            name: 'colors',
                            type: PropertyType::STRING,
                            description: "description color",
                            required: true,
                        )
                    )
                );
                $this->addProperty(
                    new ObjectProperty(
                        name: 'dimensions',
                        description: "description dimensions",
                        required: true,
                        properties: [
                            new ToolProperty(
                                name: 'width',
                                type: PropertyType::INTEGER,
                                description: "width",
                                required: true,
                            ),
                            new ToolProperty(
                                name: 'height',
                                type: PropertyType::INTEGER,
                                description: "height",
                                required: true,
                            ),
                        ]
                    )
                );
            }
            public function __invoke(mixed ...$data): array
            {
                return $data;
            }
        };

        $tool->setInputs([
            "colors" => ["red", "green", "red", "red", "green"],
            "dimensions" => [
                "width" => 600,
                "height" => 800,
            ],
        ]);

        $tool->execute();

        $this->assertEquals(
            '{"colors":["red","green","red","red","green"],"dimensions":{"width":600,"height":800}}',
            $tool->getResult()
        );
    }

    public function test_tool_named_parameters(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test_tool';
            protected ?string $description = 'description';
            public function __construct()
            {
                $this->addProperty(
                    new ToolProperty(
                        name: 'prop_3',
                        type: PropertyType::BOOLEAN,
                        description: "description prop_1",
                        required: false,
                    )
                );
                $this->addProperty(
                    new ToolProperty(
                        name: 'prop_1',
                        type: PropertyType::STRING,
                        description: "description prop_1",
                        required: true,
                    )
                );
                $this->addProperty(
                    new ToolProperty(
                        name: 'prop_2',
                        type: PropertyType::INTEGER,
                        description: "description prop_2",
                        required: true,
                    )
                );
            }
            public function __invoke(int $prop_2, string $prop_1, bool $prop_3): array
            {
                return [
                    'prop_1' => $prop_1,
                    'prop_2' => $prop_2,
                    'prop_3' => $prop_3,
                ];
            }
        };

        $input = [
            'prop_1' => 'a',
            'prop_3' => false,
            'prop_2' => 3,
        ];

        $tool->setInputs($input);

        $tool->execute();

        $this->assertEquals(
            '{"prop_1":"a","prop_2":3,"prop_3":false}',
            $tool->getResult()
        );
    }

    public function test_properties_declaration_on_method_and_constructor_with_parent_constructor(): void
    {
        $tool = new TestToolClassWithParentConstructorMixed('test');
        $this->assertCount(1, $tool->getProperties());
        $this->assertEquals('test_tool', $tool->getName());
        $this->assertEquals('test tool', $tool->getDescription());
        $this->assertEquals('test', $tool->getKey());
    }

    public function test_properties_declaration_on_method_with_parent_constructor(): void
    {
        $tool = new TestToolClassWithParentConstructor('test');
        $this->assertCount(1, $tool->getProperties());
        $this->assertEquals('test_tool', $tool->getName());
        $this->assertEquals('test tool', $tool->getDescription());
        $this->assertEquals('test', $tool->getKey());
    }

    public function test_properties_declaration_on_constructor_with_parent_constructor(): void
    {
        $tool = new TestToolClassOnlyParentConstructor('test');
        $this->assertCount(2, $tool->getProperties());
        $this->assertEquals('test_tool', $tool->getName());
        $this->assertEquals('test tool', $tool->getDescription());
        $this->assertEquals('test', $tool->getKey());
    }

    public function test_properties_declaration_on_constructor_with_parent_constructor_fluent(): void
    {
        $tool = new TestToolClassOnlyParentConstructorFluent('test');
        $this->assertCount(2, $tool->getProperties());
        $this->assertEquals('test_tool', $tool->getName());
        $this->assertEquals('test tool', $tool->getDescription());
        $this->assertEquals('test', $tool->getKey());
    }

    public function test_annotations(): void
    {
        $tool = new ToolDefinition('test', 'test');
        $this->assertSame([], $tool->getAnnotations());

        $tool = new ToolDefinition(
            name: 'test',
            description: 'test',
            annotations: ['foo' => 'bar'],
        );
        $this->assertEquals(['foo' => 'bar'], $tool->getAnnotations());
    }

    public function test_parameters(): void
    {
        $tool = new ToolDefinition('test', 'test');
        $this->assertSame([], $tool->getAnnotations());

        $tool = new ToolDefinition(
            name: 'test',
            description: 'test',
            parameters: ['foo' => 'bar'],
        );
        $this->assertEquals(['foo' => 'bar'], $tool->getParameters());

        $tool->setParameters(['foo' => 'baz']);
        $this->assertEquals(['foo' => 'baz'], $tool->getParameters());
    }
}
