<?php

declare(strict_types=1);

namespace NeuronAI\Tests\Tools;

use NeuronAI\Exceptions\MissingCallbackParameter;
use NeuronAI\Exceptions\ToolCallableNotSet;
use NeuronAI\Tests\StructuredOutput\Stub\Color;
use NeuronAI\Tests\Support\ToolErrorAssertions;
use NeuronAI\Tests\Tools\Stub\StrictApprovalTool;
use NeuronAI\Tests\Tools\Stub\TestToolClassOnlyParentConstructor;
use NeuronAI\Tests\Tools\Stub\TestToolClassOnlyParentConstructorFluent;
use NeuronAI\Tests\Tools\Stub\TestToolClassWithParentConstructor;
use NeuronAI\Tests\Tools\Stub\TestToolClassWithParentConstructorMixed;
use NeuronAI\Tools\ArrayProperty;
use NeuronAI\Tools\ObjectProperty;
use NeuronAI\Tools\PropertyType;
use NeuronAI\Tools\Tool;
use NeuronAI\Tools\ToolInterface;
use NeuronAI\Tools\ToolProperty;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;
use Error;

use function array_map;
use function array_unique;
use function json_encode;

class ToolTest extends TestCase
{
    use ToolErrorAssertions;

    public function test_tool_instance(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'example';
            protected ?string $description = 'example';

            public function __invoke(): void
            {
            }
        };
        $this->assertInstanceOf(ToolInterface::class, $tool);

        $tool->setInputs(null);
        $this->assertEquals([], $tool->getInputs());

        $tool->setCallId(null); // Tool call ID is not generated by all providers
        $this->assertEquals(null, $tool->getCallId());
        $tool->setCallId('test');
        $this->assertEquals('test', $tool->getCallId());
    }

    public function test_inputs_are_cast_to_the_declared_types(): void
    {
        $tool = $this->doublingTool();

        $tool->setInputs(['n' => '5'])->execute();

        $this->assertSame('10', $tool->getResult());
    }

    public function test_an_input_of_the_wrong_type_is_a_tool_error(): void
    {
        $tool = $this->doublingTool();

        $tool->setInputs(['n' => 'five'])->execute();

        $this->assertToolError('Parameter "n" must be of type integer, string given.', $tool->getResult());
    }

    public function test_bound_inputs_are_the_cast_values(): void
    {
        $tool = (new StrictApprovalTool())->setInputs(['permanent' => 'true', 'account_id' => ' 1']);

        $this->assertSame(['permanent' => true, 'account_id' => 1], $tool->getInputs());
    }

    public function test_get_input_reads_one_cast_value_and_null_when_it_is_absent(): void
    {
        $tool = (new StrictApprovalTool())->setInputs(['permanent' => 'false']);

        $this->assertFalse($tool->getInput('permanent'));
        $this->assertNull($tool->getInput('account_id'));
    }

    public function test_a_rejected_binding_keeps_the_model_inputs_verbatim(): void
    {
        $inputs = ['permanent' => 'true', 'account_id' => 'one'];

        $tool = (new StrictApprovalTool())->setInputs($inputs);

        $this->assertSame($inputs, $tool->getInputs());
    }

    public function test_the_first_rejected_parameter_in_declaration_order_is_reported(): void
    {
        $tool = (new StrictApprovalTool())->setInputs(['account_id' => 'one', 'permanent' => 'maybe']);

        $tool->execute();

        $this->assertToolError('Parameter "permanent" must be of type boolean, string given.', $tool->getResult());
    }

    public function test_approval_policy_reads_the_cast_inputs(): void
    {
        $tool = (new StrictApprovalTool())->setInputs(['permanent' => 'true', 'account_id' => '1']);

        $this->assertSame('Permanent deletion', $tool->requiresApproval());
    }

    public function test_approval_policy_override_reads_the_cast_inputs(): void
    {
        $tool = (new StrictApprovalTool())
            ->withApprovalPolicy(fn (ToolInterface $tool): bool => $tool->getInputs()['account_id'] === 1)
            ->setInputs(['permanent' => false, 'account_id' => '1']);

        $this->assertTrue($tool->requiresApproval());
    }

    public function test_run_key_is_the_same_for_every_spelling_of_an_input(): void
    {
        $tool = new StrictApprovalTool();

        $keys = array_map(
            fn (mixed $accountId): string => $tool->setInputs(['permanent' => true, 'account_id' => $accountId])->getRunKey(),
            [1, '1', " 1\n"],
        );

        $this->assertCount(1, array_unique($keys));
    }

    public function test_an_input_of_the_wrong_type_is_never_gated_nor_invoked(): void
    {
        $tool = new StrictApprovalTool();
        $tool->requireApproval()
            ->setInputs(['permanent' => true, 'account_id' => 'one']);

        $this->assertFalse($tool->requiresApproval());

        $tool->execute();

        $this->assertSame(0, $tool->invocations);
        $this->assertToolError('Parameter "account_id" must be of type integer, string given.', $tool->getResult());
    }

    public function test_binding_valid_inputs_clears_a_previous_rejection(): void
    {
        $tool = (new StrictApprovalTool())->setInputs(['permanent' => true, 'account_id' => 'one']);

        $tool->setInputs(['permanent' => true, 'account_id' => 1])->execute();

        $this->assertSame('deleted', $tool->getResult());
    }

    protected function doublingTool(): Tool
    {
        return new class () extends Tool {
            protected string $name = 'double';

            protected function properties(): array
            {
                return [new ToolProperty('n', PropertyType::INTEGER, 'An integer', true)];
            }

            public function __invoke(int $n): int
            {
                return $n * 2;
            }
        };
    }

    public function test_required_properties(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test';
            protected ?string $description = 'Test tool';
            public function __construct()
            {
                $this->addProperty(new ToolProperty('name', PropertyType::STRING, 'User name', true));
                $this->addProperty(new ToolProperty('surname', PropertyType::STRING, 'User surname', false));
                $this->addProperty(new ToolProperty('age', PropertyType::INTEGER, 'User age', true));
            }
            public function __invoke(): void
            {
            }
        };

        $properties = $tool->getRequiredProperties();
        $this->assertEquals(['name', 'age'], $properties);
    }

    /**
     * @param array<string, mixed> $inputs
     */
    #[DataProvider('inputsMissingARequiredParameter')]
    public function test_missing_required_parameter_is_an_exception_and_never_invokes(array $inputs): void
    {
        $tool = new StrictApprovalTool();
        $tool->setInputs($inputs);

        try {
            $tool->execute();
            $this->fail('A missing required parameter must throw.');
        } catch (MissingCallbackParameter $exception) {
            $this->assertSame('Missing required parameter: account_id', $exception->getMessage());
        }

        $this->assertSame(0, $tool->invocations);
        $this->assertFalse($tool->hasResult());
    }

    public static function inputsMissingARequiredParameter(): array
    {
        return [
            'absent' => [['permanent' => true]],
            'only an undeclared key with a similar name' => [['permanent' => true, 'accountId' => 1]],
        ];
    }

    public function test_required_properties_with_mapped_object(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test';
            protected ?string $description = 'Test tool';
            public function __construct()
            {
                $this->addProperty(new ObjectProperty(
                    name: 'name',
                    description: 'User name',
                    required: true,
                    class: Color::class
                ));
            }
            public function __invoke(): void
            {
            }
        };

        $toolRequiredProperties = $tool->getRequiredProperties();
        /** @var ObjectProperty $objProperty */
        $objProperty = $tool->getProperties()[0];
        $objRequiredProperties = $objProperty->getRequiredProperties();
        $this->assertEquals(['name'], $toolRequiredProperties);
        $this->assertEquals(['r', 'g', 'b'], $objRequiredProperties);
    }

    public function test_tool_return_value(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test';
            protected ?string $description = 'Test tool';
            public function __invoke(): string
            {
                return 'test';
            }
        };
        $tool->execute();
        $this->assertEquals('test', $tool->getResult());

        $tool = new class () extends Tool {
            protected string $name = 'test';
            protected ?string $description = 'Test tool';
            public function __invoke(): array
            {
                return ['test'];
            }
        };
        $tool->execute();
        $this->assertEquals('["test"]', $tool->getResult());

        $tool = new class () extends Tool {
            protected string $name = 'test';
            protected ?string $description = 'Test tool';
            public function __invoke(): array
            {
                return ['foo' => 'bar'];
            }
        };
        $tool->execute();
        $this->assertEquals('{"foo":"bar"}', $tool->getResult());

        $tool = new class () extends Tool {
            protected string $name = 'test';
            protected ?string $description = 'Test tool';
            public function __invoke(): object
            {
                return new class () {
                    public function __toString(): string
                    {
                        return 'test';
                    }
                };
            }
        };
        $tool->execute();
        $this->assertEquals('test', $tool->getResult());
    }

    public function test_invalid_return_type(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test';
            protected ?string $description = 'Test tool';
            public function __invoke(): object
            {
                return new class () {};
            }
        };

        $this->expectException(Error::class);
        $this->expectExceptionMessageMatches('/^Object of class .+ could not be converted to string$/');

        $tool->execute();
    }

    public function test_tool_optional_parameters(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test_tool';
            protected ?string $description = 'description';
            public function __construct()
            {
                $this->addProperty(new ToolProperty(
                    name: 'optional_prop_1',
                    type: PropertyType::STRING,
                    description: "description",
                    required: false,
                ));
                $this->addProperty(new ToolProperty(
                    name: 'optional_prop_2',
                    type: PropertyType::STRING,
                    description: "description",
                    required: false,
                ));
                $this->addProperty(new ToolProperty(
                    name: 'optional_prop_3',
                    type: PropertyType::STRING,
                    description: "description",
                    required: false,
                ));
            }
            public function __invoke(?string $optional_prop_1, ?string $optional_prop_2, ?string $optional_prop_3): array
            {
                return [
                    'optional_prop_1' => $optional_prop_1,
                    'optional_prop_2' => $optional_prop_2,
                    'optional_prop_3' => $optional_prop_3,
                ];
            }
        };

        // Example: none of the optional parameters are provided
        $tool->setInputs([]);

        $tool->execute();

        $this->assertEquals(
            '{"optional_prop_1":null,"optional_prop_2":null,"optional_prop_3":null}',
            $tool->getResult()
        );
    }

    public function test_tool_variadic_invocation_basic_properties(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'user_manager';
            protected ?string $description = 'Update user information';
            public function __construct()
            {
                $this->addProperty(new ToolProperty(
                    name: 'lastname',
                    type: PropertyType::STRING,
                    description: "The user lastname",
                    required: false,
                ));
                $this->addProperty(new ToolProperty(
                    name: 'firstname',
                    type: PropertyType::STRING,
                    description: "The user firstname",
                    required: false,
                ));
                $this->addProperty(new ToolProperty(
                    name: 'email',
                    type: PropertyType::STRING,
                    description: "The user email",
                    required: true,
                ));
                $this->addProperty(new ToolProperty(
                    name: 'language',
                    type: PropertyType::STRING,
                    description: "The user's language",
                    required: true,
                    enum: ['fr', 'en', 'it', 'de', 'es'],
                ));
            }
            public function __invoke(mixed ...$data): array
            {
                return $data;
            }
        };

        // Example: the user's last name is not provided
        $tool->setInputs([
            "firstname" => "John",
            "email" => "john.doe@example.com",
            "language" => "fr",
        ]);

        $tool->execute();

        $this->assertEquals(
            '{"lastname":null,"firstname":"John","email":"john.doe@example.com","language":"fr"}',
            $tool->getResult()
        );
    }

    public function test_tool_variadic_invocation_object_properties(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test_tool';
            protected ?string $description = 'description';
            public function __construct()
            {
                $this->addProperty(
                    new ObjectProperty(
                        name: 'obj_prop_1',
                        description: "description obj_prop_1",
                        required: true,
                        properties: [
                            new ToolProperty(
                                name: 'a',
                                type: PropertyType::STRING,
                                description: "description a",
                                required: true,
                            ),
                            new ToolProperty(
                                name: 'b',
                                type: PropertyType::STRING,
                                description: "description b",
                                required: true,
                            ),
                        ]
                    )
                );
                $this->addProperty(
                    new ObjectProperty(
                        name: 'obj_prop_2',
                        description: "description obj_prop_2",
                        required: false,
                        properties: [
                                new ToolProperty(
                                    name: 'x',
                                    type: PropertyType::STRING,
                                    description: "description x",
                                    required: true,
                                ),
                                new ToolProperty(
                                    name: 'y',
                                    type: PropertyType::STRING,
                                    description: "description y",
                                    required: true,
                                ),
                            ]
                    )
                );
            }
            public function __invoke(mixed ...$data): array
            {
                return $data;
            }
        };

        // Example, the second object property is not provided
        $tool->setInputs([
            "obj_prop_1" => [
                "a" => "a_input",
                "b" => "b_input",
            ],
        ]);

        $tool->execute();

        $this->assertEquals(
            '{"obj_prop_1":{"a":"a_input","b":"b_input"},"obj_prop_2":null}',
            $tool->getResult()
        );
    }

    public function test_tool_variadic_invocation_mapped_object_properties(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test_tool';
            protected ?string $description = 'description';
            public function __construct()
            {
                $this->addProperty(
                    new ObjectProperty(
                        name: 'color',
                        description: "description color",
                        required: true,
                        class: Color::class
                    )
                );
            }
            public function __invoke(mixed ...$data): array
            {
                return $data;
            }
        };

        $tool->setInputs([
            "color" => [
                "r" => 255,
                "g" => 127,
                "b" => 63,
            ],
        ]);

        $tool->execute();

        $this->assertEquals(
            '{"color":{"r":255,"g":127,"b":63}}',
            $tool->getResult()
        );
    }

    public function test_tool_variadic_invocation_array_properties(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test_tool';
            protected ?string $description = 'description';
            public function __construct()
            {
                $this->addProperty(
                    new ArrayProperty(
                        name: 'colors',
                        description: "description color",
                        required: true,
                        items: new ToolProperty(
                            name: 'colors',
                            type: PropertyType::STRING,
                            description: "description color",
                            required: true,
                        )
                    )
                );
                $this->addProperty(
                    new ObjectProperty(
                        name: 'dimensions',
                        description: "description dimensions",
                        required: true,
                        properties: [
                            new ToolProperty(
                                name: 'width',
                                type: PropertyType::INTEGER,
                                description: "width",
                                required: true,
                            ),
                            new ToolProperty(
                                name: 'height',
                                type: PropertyType::INTEGER,
                                description: "height",
                                required: true,
                            ),
                        ]
                    )
                );
            }
            public function __invoke(mixed ...$data): array
            {
                return $data;
            }
        };

        $tool->setInputs([
            "colors" => ["red", "green", "red", "red", "green"],
            "dimensions" => [
                "width" => 600,
                "height" => 800,
            ],
        ]);

        $tool->execute();

        $this->assertEquals(
            '{"colors":["red","green","red","red","green"],"dimensions":{"width":600,"height":800}}',
            $tool->getResult()
        );
    }

    public function test_tool_named_parameters(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test_tool';
            protected ?string $description = 'description';
            public function __construct()
            {
                $this->addProperty(
                    new ToolProperty(
                        name: 'prop_3',
                        type: PropertyType::BOOLEAN,
                        description: "description prop_1",
                        required: false,
                    )
                );
                $this->addProperty(
                    new ToolProperty(
                        name: 'prop_1',
                        type: PropertyType::STRING,
                        description: "description prop_1",
                        required: true,
                    )
                );
                $this->addProperty(
                    new ToolProperty(
                        name: 'prop_2',
                        type: PropertyType::INTEGER,
                        description: "description prop_2",
                        required: true,
                    )
                );
            }
            public function __invoke(int $prop_2, string $prop_1, bool $prop_3): array
            {
                return [
                    'prop_1' => $prop_1,
                    'prop_2' => $prop_2,
                    'prop_3' => $prop_3,
                ];
            }
        };

        $input = [
            'prop_1' => 'a',
            'prop_3' => false,
            'prop_2' => 3,
        ];

        $tool->setInputs($input);

        $tool->execute();

        $this->assertEquals(
            '{"prop_1":"a","prop_2":3,"prop_3":false}',
            $tool->getResult()
        );
    }

    public function test_properties_declaration_on_method_and_constructor_with_parent_constructor(): void
    {
        $tool = new TestToolClassWithParentConstructorMixed('test');
        $this->assertCount(1, $tool->getProperties());
        $this->assertEquals('test_tool', $tool->getName());
        $this->assertEquals('test tool', $tool->getDescription());
        $this->assertEquals('test', $tool->getKey());
    }

    public function test_properties_declaration_on_method_with_parent_constructor(): void
    {
        $tool = new TestToolClassWithParentConstructor('test');
        $this->assertCount(1, $tool->getProperties());
        $this->assertEquals('test_tool', $tool->getName());
        $this->assertEquals('test tool', $tool->getDescription());
        $this->assertEquals('test', $tool->getKey());
    }

    public function test_properties_declaration_on_constructor_with_parent_constructor(): void
    {
        $tool = new TestToolClassOnlyParentConstructor('test');
        $this->assertCount(2, $tool->getProperties());
        $this->assertEquals('test_tool', $tool->getName());
        $this->assertEquals('test tool', $tool->getDescription());
        $this->assertEquals('test', $tool->getKey());
    }

    public function test_properties_declaration_on_constructor_with_parent_constructor_fluent(): void
    {
        $tool = new TestToolClassOnlyParentConstructorFluent('test');
        $this->assertCount(2, $tool->getProperties());
        $this->assertEquals('test_tool', $tool->getName());
        $this->assertEquals('test tool', $tool->getDescription());
        $this->assertEquals('test', $tool->getKey());
    }

    public function test_track_by_inputs_run_key(): void
    {
        $tool = new class () extends Tool {
            use \NeuronAI\Tools\TrackByInputs;

            protected string $name = 'read_file';

            public function __invoke(): void
            {
            }
        };

        $tool->setInputs(['path' => '/tmp/a']);
        $keyA = $tool->getRunKey();
        $tool->setInputs(['path' => '/tmp/b']);
        $keyB = $tool->getRunKey();

        $this->assertStringStartsWith('read_file:', $keyA);
        $this->assertNotSame($keyA, $keyB, 'Different inputs must produce different run keys');
    }

    public function test_annotations(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test';
            protected array $annotations = ['foo' => 'bar'];

            public function __invoke(): void
            {
            }
        };
        $this->assertEquals(['foo' => 'bar'], $tool->getAnnotations());
    }

    public function test_parameters(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'test';
            protected array $parameters = ['foo' => 'bar'];

            public function __invoke(): void
            {
            }
        };
        $this->assertEquals(['foo' => 'bar'], $tool->getParameters());

        $tool->setParameters(['foo' => 'baz']);
        $this->assertEquals(['foo' => 'baz'], $tool->getParameters());
    }

    public function test_undeclared_inputs_never_reach_invoke(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'echo';

            protected function properties(): array
            {
                return [new ToolProperty('text', PropertyType::STRING, 'Text', true)];
            }

            public function __invoke(mixed ...$arguments): array
            {
                return $arguments;
            }
        };

        $tool->setInputs(['text' => 'hi', 'path' => '/etc/passwd', 'text2' => 'x'])->execute();

        $this->assertSame('{"text":"hi"}', $tool->getResult());
    }

    public function test_a_tool_without_invoke_cannot_execute(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'incomplete';
        };

        $this->expectException(ToolCallableNotSet::class);
        $this->expectExceptionMessage('Tool "incomplete" must implement __invoke() to define its execution logic.');

        $tool->execute();
    }

    public function test_input_schema_lists_properties_and_required_names_in_declaration_order(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'search';

            protected function properties(): array
            {
                return [
                    new ToolProperty('query', PropertyType::STRING, 'The query', true),
                    new ToolProperty('limit', PropertyType::INTEGER, nullable: true),
                    new ArrayProperty('tags', items: new ToolProperty('tag', PropertyType::STRING), required: true),
                ];
            }
        };

        $this->assertSame([
            'type' => 'object',
            'properties' => [
                'query' => ['type' => 'string', 'description' => 'The query'],
                'limit' => ['type' => ['integer', 'null']],
                'tags' => ['type' => 'array', 'items' => ['type' => 'string']],
            ],
            'required' => ['query', 'tags'],
        ], $tool->getInputSchema());
    }

    public function test_input_schema_without_properties_encodes_properties_as_a_json_object(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'now';
        };

        $this->assertSame('{"type":"object","properties":{},"required":[]}', json_encode($tool->getInputSchema()));
    }

    public function test_properties_hook_is_consulted_once(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'counter';

            public int $hookCalls = 0;

            protected function properties(): array
            {
                $this->hookCalls++;

                return [new ToolProperty('n', PropertyType::INTEGER)];
            }
        };

        $tool->getProperties();
        $tool->getInputSchema();
        $tool->setInputs(['n' => 1]);

        $this->assertSame(1, $tool->hookCalls);
        $this->assertCount(1, $tool->getProperties());
    }

    public function test_json_serialization_carries_the_call_but_never_the_dependencies(): void
    {
        $tool = new class ('sk-secret-api-key') extends Tool {
            protected string $name = 'transcribe';
            protected ?string $description = 'Transcribe a video';

            public function __construct(protected string $apiKey)
            {
            }

            protected function properties(): array
            {
                return [new ToolProperty('url', PropertyType::STRING, required: true)];
            }

            public function __invoke(string $url): string
            {
                return 'transcript';
            }
        };

        $tool->setCallId('call_1')->setInputs(['url' => 'https://example.com/v'])->execute();

        $this->assertSame(
            '{"callId":"call_1","name":"transcribe","description":"Transcribe a video","parameters":[],"inputs":{"url":"https:\\/\\/example.com\\/v"},"result":"transcript"}',
            json_encode($tool)
        );
        $this->assertStringNotContainsString('sk-secret-api-key', json_encode($tool));
    }

    public function test_json_serialization_encodes_empty_inputs_as_an_object(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'now';
        };

        $this->assertSame('{}', json_encode($tool->jsonSerialize()['inputs']));
    }

    public function test_a_void_tool_settles_with_an_empty_result(): void
    {
        $tool = new class () extends Tool {
            protected string $name = 'fire_and_forget';

            public function __invoke(): void
            {
            }
        };

        $this->assertFalse($tool->hasResult());

        $tool->execute();

        $this->assertTrue($tool->hasResult());
        $this->assertSame('', $tool->getResult());
    }

    public function test_run_key_is_the_tool_name_by_default(): void
    {
        $tool = (new StrictApprovalTool())->setName('custom_name');
        $plain = $this->doublingTool()->setInputs(['n' => 1]);

        $this->assertSame('double', $plain->getRunKey());
        $this->assertSame('double', $plain->setInputs(['n' => 2])->getRunKey());
        $this->assertStringStartsWith('custom_name:', $tool->setInputs(['permanent' => true, 'account_id' => 1])->getRunKey());
    }

    public function test_track_by_inputs_run_key_is_stable_for_equal_inputs(): void
    {
        $tool = new StrictApprovalTool();

        $first = $tool->setInputs(['permanent' => false, 'account_id' => 7])->getRunKey();
        $second = (new StrictApprovalTool())->setInputs(['permanent' => false, 'account_id' => 7])->getRunKey();

        $this->assertSame($first, $second);
        $this->assertMatchesRegularExpression('/^delete_account:[0-9a-f]{40}$/', $first);
    }
}
