<?php

declare(strict_types=1);

namespace NeuronAI\Tools;

use NeuronAI\Exceptions\MissingCallbackParameter;
use NeuronAI\Exceptions\ToolCallableNotSet;
use NeuronAI\StaticConstructor;
use NeuronAI\StructuredOutput\Deserializer\Deserializer;
use NeuronAI\StructuredOutput\Deserializer\DeserializerException;
use ReflectionClass;
use ReflectionException;
use stdClass;

use function array_key_exists;
use function array_map;
use function array_reduce;
use function is_array;
use function json_encode;
use function method_exists;
use function sprintf;

/**
 * @method static static make(...$arguments)
 */
abstract class Tool implements ToolInterface
{
    use StaticConstructor;

    protected string $name;

    protected ?string $description = null;

    /**
     * @var ToolPropertyInterface[]
     */
    protected array $properties = [];

    protected array $parameters = [];

    protected array $annotations = [];

    /**
     * The arguments to pass in to the tool callback.
     */
    protected array $inputs = [];

    /**
     * The call ID generated by the LLM.
     */
    protected ?string $callId = null;

    /**
     * The result of the execution.
     */
    protected string|ToolOutput|null $result = null;

    /**
     * Approval state of this specific call (ADR 0003). Null = not approval-gated.
     */
    protected ?ApprovalState $approvalState = null;

    /**
     * Rejection reason. Only ever non-null when $approvalState is Rejected.
     */
    protected ?string $rejectReason = null;

    /**
     * Why this call is asking for approval — the tool author's (or middleware
     * config's) outbound message to the approver. Stamped by ToolApproval when
     * requiresApproval() or a config callback returns a string.
     */
    protected ?string $approvalReason = null;

    /**
     * Define the maximum number of calls for the tool in a single agent session.
     */
    protected ?int $maxRuns = null;

    protected bool $visible = true;

    /**
     * True when this instance was rebuilt from a persisted snapshot: __serialize()
     * drops subclass dependencies (connections, clients, closures), so the tool
     * carries its call data but cannot execute. ToolNode swaps dehydrated tools
     * for fresh clones from the live registry before execution.
     */
    protected bool $dehydrated = false;

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): ToolInterface
    {
        $this->name = $name;
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): ToolInterface
    {
        $this->description = $description;
        return $this;
    }

    public function addProperty(ToolPropertyInterface $property): ToolInterface
    {
        $this->properties[] = $property;
        return $this;
    }

    /**
     * @return ToolPropertyInterface[]
     */
    protected function properties(): array
    {
        return [];
    }

    /**
     * @return ToolPropertyInterface[]
     */
    public function getProperties(): array
    {
        if ($this->properties === []) {
            foreach ($this->properties() as $property) {
                $this->addProperty($property);
            }
        }

        return $this->properties;
    }

    public function getRequiredProperties(): array
    {
        return array_reduce($this->getProperties(), function (array $carry, ToolPropertyInterface $property): array {
            if ($property->isRequired()) {
                $carry[] = $property->getName();
            }

            return $carry;
        }, []);
    }

    public function getAnnotations(): array
    {
        return $this->annotations;
    }

    public function setParameters(array $parameters): self
    {
        $this->parameters = $parameters;
        return $this;
    }

    public function getParameters(): array
    {
        return $this->parameters;
    }

    public function getInputs(): array
    {
        return $this->inputs;
    }

    public function getInput(string $key): mixed
    {
        return $this->inputs[$key] ?? null;
    }

    public function setInputs(?array $inputs): self
    {
        $this->inputs = $inputs ?? [];
        return $this;
    }

    public function getCallId(): ?string
    {
        return $this->callId;
    }

    public function setCallId(?string $callId): self
    {
        $this->callId = $callId;
        return $this;
    }

    public function hasResult(): bool
    {
        return $this->result !== null;
    }

    public function getResult(): string|ToolOutput
    {
        return $this->result;
    }

    public function setResult(mixed $result): ToolInterface
    {
        if ($result instanceof ToolOutput) {
            $this->result = $result;
        } else {
            $this->result = is_array($result) ? json_encode($result) : (string) $result;
        }

        return $this;
    }

    public function getMaxRuns(): ?int
    {
        return $this->maxRuns;
    }

    public function setMaxRuns(int $tries): self
    {
        $this->maxRuns = $tries;
        return $this;
    }

    public function visible(bool $visible): ToolInterface
    {
        $this->visible = $visible;
        return $this;
    }

    public function isVisible(): bool
    {
        return $this->visible;
    }

    public function getRunKey(): string
    {
        return $this->getName();
    }

    public function requiresApproval(array $inputs): bool|string
    {
        return false;
    }

    public function getApprovalReason(): ?string
    {
        return $this->approvalReason;
    }

    public function setApprovalReason(?string $reason): ToolInterface
    {
        $this->approvalReason = $reason;
        return $this;
    }

    public function getApprovalState(): ?ApprovalState
    {
        return $this->approvalState;
    }

    public function setApprovalState(ApprovalState $state, ?string $reason = null): ToolInterface
    {
        $this->approvalState = $state;
        $this->rejectReason = $state === ApprovalState::Rejected ? $reason : null;
        return $this;
    }

    public function getRejectReason(): ?string
    {
        return $this->rejectReason;
    }

    /**
     * Execute the client side function.
     *
     * @throws MissingCallbackParameter
     * @throws ToolCallableNotSet
     * @throws DeserializerException
     * @throws ReflectionException
     */
    public function execute(): void
    {
        if (!method_exists($this, '__invoke')) {
            throw new ToolCallableNotSet(sprintf(
                'Tool "%s" must implement __invoke() to define its execution logic.',
                $this->name,
            ));
        }

        // Validate required parameters
        foreach ($this->getProperties() as $property) {
            if ($property->isRequired() && !array_key_exists($property->getName(), $this->getInputs())) {
                throw new MissingCallbackParameter("Missing required parameter: {$property->getName()}");
            }
        }

        $parameters = array_reduce($this->getProperties(), function (array $carry, ToolPropertyInterface $property): array {
            $propertyName = $property->getName();
            $inputs = $this->getInputs();

            // Normalize missing optional properties by assigning them a null value
            // Treat it as explicitly null to ensure a consistent structure
            if (!array_key_exists($propertyName, $inputs)) {
                $carry[$propertyName] = null;
                return $carry;
            }

            // Find the corresponding input value
            $inputValue = $inputs[$propertyName];

            // If there is an object property with a class definition,
            // deserialize the tool input into an instance of that class
            if ($property instanceof ObjectProperty && $property->getClass()) {
                $carry[$propertyName] = Deserializer::make()->fromJson(json_encode($inputValue), $property->getClass());
                return $carry;
            }

            // If a property is an array of objects and each item matches a class definition,
            // deserialize each item into an instance of that class
            if ($property instanceof ArrayProperty) {
                $items = $property->getItems();
                if ($items instanceof ObjectProperty && $items->getClass()) {
                    $class = $items->getClass();
                    $carry[$propertyName] = array_map(fn (array|object $input): object => Deserializer::make()->fromJson(json_encode($input), $class), $inputValue);
                    return $carry;
                }
            }

            // No extra treatments for basic property types
            $carry[$propertyName] = $inputValue;
            return $carry;

        }, []);

        $this->setResult($this->__invoke(...$parameters));
    }

    public function isDehydrated(): bool
    {
        return $this->dehydrated;
    }

    /**
     * The persisted form of a tool is data-only. The contract: properties declared
     * on the Tool base class are call data and survive serialization; properties
     * declared below it are execution capability (DB connections, HTTP clients,
     * closures) and are dropped — capability is never persisted, it is re-supplied
     * by the live process on replay via rehydrate(). Without this, attaching a
     * durable persistence backend would fail on any tool holding a non-serializable
     * dependency (e.g. "Serialization of 'Pdo\Mysql' is not allowed" with the
     * MySQL toolkit).
     *
     * @return array<string, mixed>
     */
    public function __serialize(): array
    {
        // Materialize the schema so the snapshot keeps it even when a subclass
        // builds properties() from a dependency that is dropped.
        $this->getProperties();

        $data = [];
        foreach ((new ReflectionClass(self::class))->getProperties() as $property) {
            if ($property->getName() !== 'dehydrated' && $property->isInitialized($this)) {
                $data[$property->getName()] = $property->getValue($this);
            }
        }

        return $data;
    }

    /**
     * @param array<string, mixed> $data
     */
    public function __unserialize(array $data): void
    {
        foreach ($data as $name => $value) {
            $this->{$name} = $value;
        }

        $this->dehydrated = true;
    }

    /**
     * Restore execution capability onto a dehydrated instance by transplanting
     * the subclass-declared properties — the ones __serialize() dropped — from a
     * live donor of the same class. The inverse of dehydration: the call data
     * stays untouched, the shell already owns it. Skips silently when the donor
     * is missing or of a different class (code drift between suspend and
     * recovery): a dependency-free shell is still executable as-is.
     */
    public function rehydrate(?ToolInterface $donor): void
    {
        if ($donor === null || $donor::class !== $this::class) {
            return;
        }

        foreach ((new ReflectionClass($this))->getProperties() as $property) {
            if ($property->isStatic() || $property->getDeclaringClass()->getName() === self::class) {
                continue;
            }

            if ($property->isInitialized($donor)) {
                $property->setValue($this, $property->getValue($donor));
            }
        }

        $this->dehydrated = false;
    }

    public function jsonSerialize(): array
    {
        return [
            'callId' => $this->callId,
            'name' => $this->name,
            'description' => $this->description,
            'parameters' => $this->parameters,
            'inputs' => $this->inputs === [] ? new stdClass() : $this->inputs,
            'result' => $this->result instanceof ToolOutput ? $this->result->jsonSerialize() : $this->result,
            'approval' => $this->approvalState?->value,
            'approvalReason' => $this->approvalReason,
            'rejectReason' => $this->rejectReason,
        ];
    }
}
