<?php

declare(strict_types=1);

namespace NeuronAI\Tools;

use JsonSerializable;

interface ToolInterface extends JsonSerializable
{
    public function getName(): string;

    public function setName(string $name): ToolInterface;

    public function getDescription(): ?string;

    public function setDescription(?string $description): ToolInterface;

    public function addProperty(ToolPropertyInterface $property): ToolInterface;

    /**
     * @return ToolPropertyInterface[]
     */
    public function getProperties(): array;

    /**
     * @return array<string>
     */
    public function getRequiredProperties(): array;

    public function getParameters(): array;

    public function getInputs(): array;

    public function getInput(string $key): mixed;

    public function setInputs(array $inputs): ToolInterface;

    /**
     * The call identifier generated by the LLM.
     */
    public function getCallId(): ?string;

    public function setCallId(string $callId): ToolInterface;

    /**
     * Whether the tool has executed and holds a result. False for a tool that
     * never ran (e.g. a pending or rejected call), where getResult() must not
     * be called.
     */
    public function hasResult(): bool;

    /**
     * A string, or a ToolOutput when the tool returned multimodal content
     * blocks from __invoke().
     */
    public function getResult(): string|ToolOutput;

    public function setResult(mixed $result): ToolInterface;

    /**
     * The maximum number of calls for the tool in a single agent session.
     */
    public function getMaxRuns(): ?int;

    public function setMaxRuns(int $tries): ToolInterface;

    public function visible(bool $visible): ToolInterface;

    public function isVisible(): bool;

    /**
     * The key run limits are tracked by: the tool name, a hash of inputs,
     * or any custom strategy.
     */
    public function getRunKey(): string;

    public function execute(): void;

    /**
     * Whether this call requires human approval before execution, consulted by
     * ToolNode on every tool call. Returning a string counts as true AND carries
     * the reason shown to the approver (surfaced on the ApprovalRequest actions
     * and persisted in chat history).
     *
     * @param array<string, mixed> $inputs The arguments the model is calling the tool with.
     */
    public function requiresApproval(array $inputs): bool|string;
}
