<?php

declare(strict_types=1);

namespace NeuronAI\Tools;

use JsonSerializable;

interface ToolInterface extends JsonSerializable
{
    /**
     * Get the unique name of the tool.
     */
    public function getName(): string;

    public function setName(string $name): ToolInterface;

    /**
     * Get a description of the tool's functionality.
     */
    public function getDescription(): ?string;

    public function setDescription(?string $description): ToolInterface;

    /**
     * Add a Property with a name, type, description, and optional required constraint.
     */
    public function addProperty(ToolPropertyInterface $property): ToolInterface;

    /**
     * Get the Properties schema.
     */
    public function getProperties(): array;

    /**
     * Names of the required properties.
     *
     * @return array<string>
     */
    public function getRequiredProperties(): array;

    public function getParameters(): array;

    /**
     * Get the input arguments of the function call.
     */
    public function getInputs(): array;

    public function getInput(string $key): mixed;

    /**
     * Get the input arguments of the function call.
     */
    public function setInputs(array $inputs): ToolInterface;

    /**
     * The call identifier generated by the LLM.
     */
    public function getCallId(): ?string;


    public function setCallId(string $callId): ToolInterface;


    /**
     * Whether the tool has executed and holds a result. False for a tool
     * that never ran (e.g. a pending or rejected call), where getResult()
     * must not be called.
     */
    public function hasResult(): bool;

    /**
     * The result of the execution: a string, or a ToolOutput when the tool
     * returned multimodal content blocks from __invoke().
     */
    public function getResult(): string|ToolOutput;

    public function setResult(mixed $result): ToolInterface;

    /**
     * Define the maximum number of calls for the tool in a single agent session.
     */
    public function getMaxRuns(): ?int;

    public function setMaxRuns(int $tries): ToolInterface;

    public function visible(bool $visible): ToolInterface;

    public function isVisible(): bool;

    /**
     * Get a unique key for tracking tool runs.
     *
     * Tools can return any string — the tool name itself, a hash of inputs,
     * a combination of specific parameter values, or any custom strategy.
     */
    public function getRunKey(): string;

    /**
     * Execute the tool's logic with input parameters.
     */
    public function execute(): void;

    /**
     * Whether this tool call requires human approval before execution (ADR 0004).
     * Consulted only when the ToolApproval middleware is attached to the agent;
     * middleware configuration overrides this declaration in both directions.
     *
     * Returning a string counts as true AND carries the reason the approval is
     * being requested — surfaced to the approver via the ApprovalRequest actions
     * and the tool entries persisted in chat history.
     *
     * @param array<string, mixed> $inputs The arguments the model is calling the tool with.
     */
    public function requiresApproval(array $inputs): bool|string;

    /**
     * The reason this call is asking for approval (the tool author's or middleware
     * config's outbound message to the approver). Null when no reason was declared.
     * Distinct from getRejectReason(), which is the approver's inbound feedback.
     */
    public function getApprovalReason(): ?string;

    public function setApprovalReason(?string $reason): ToolInterface;

    /**
     * The recorded approval state of this tool call, or null when the call is
     * not approval-gated (ADR 0003).
     */
    public function getApprovalState(): ?ApprovalState;

    /**
     * Record the approval state. $reason is meaningful only for rejections
     * (reject reasons are a rejection-only concept — see CONTEXT.md); pass null otherwise.
     */
    public function setApprovalState(ApprovalState $state, ?string $reason = null): ToolInterface;

    /**
     * The rejection reason recorded with a Rejected state, null otherwise.
     */
    public function getRejectReason(): ?string;
}
